# Generated by Django 5.1.7 on 2025-05-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOtp',
        ),
    ]
