# Generated by Django 5.1.7 on 2025-03-30 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Payment', 'Online Payment')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed'), ('Failed', 'failed'), ('Refunded', 'refunded')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kalti_pxid', models.CharField(max_length=255, null=True)),
                ('shipping_address', models.CharField(max_length=255, null=True)),
                ('shipping_city', models.CharField(max_length=255, null=True)),
                ('shipping_state', models.CharField(max_length=255, null=True)),
                ('shipping_zip', models.CharField(max_length=255, null=True)),
                ('shipping_country', models.CharField(max_length=255, null=True)),
                ('shipping_phone', models.CharField(max_length=255, null=True)),
                ('billing_address', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
